Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: wordpress-
    SupplierDeployMetadata:
      HelmChartArtifactRelation:
        '{{ computenest::helmchart::wordpress }}':
          ArtifactId: artifact-45b453fa72fb43d2833b
    TemplateConfigs:
      - Name: 容器集群
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
          - cn-shanghai
          - cn-qingdao
          - cn-beijing
          - cn-huhehaote
          - cn-wulanchabu
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-chengdu
          - cn-hongkong
          - ap-southeast-1
          - ap-northeast-2
          - ap-southeast-3
          - ap-southeast-5
          - ap-northeast-1
          - eu-central-1
          - eu-west-1
          - us-west-1
          - us-east-1
          - ap-southeast-6
          - ap-southeast-7
        ArchitectureDiagramUrl: 'docs/architecture.png'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: wordpress demo，在容器集群上以helm chart的方式部署wordpress应用
    Image: 'resources/icons/service_logo.png'
    Name: Wordpress服务示例(容器集群+helm版本)
  ShareType: Public
  ApprovalType: Manual
  UpgradeMetadata:
    Description: 升级
    SupportRollback: true
    UpgradeComponents:
      - Configuration
      - Resource
HelmChartBuilder:
  HelmChart_1:
    HelmChartPath: 'resources/artifact_resources/helm_chart/wordpress-15.4.1.tgz'
    RepoName: wordpress
    Tag: 15.4.1